name: ✅ Build Check for PowerGuard

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: ✅ Ping Success
        run: echo "Workflow is working fine! ✅"
